name: NodeJS build and create release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
        
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: actual-tcb-sync
        path: build
    - name: Zip build for release
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r actual-tcb-sync.zip build
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        title: Actual TCB Sync
        automatic_release_tag: latest
        files: |
          actual-tcb-sync.zip
